configfile: "config/config.yaml"


rule all:
    input:
        expand("results/{sample}/result.tsv", sample=config["samples"]),
        expand("results/{sample}/amplicons.fas", sample=config["samples"]),


rule prep:
    """
    Create FASTA file for the primers and probes from config
    """
    input:
        tsv="config/primers.tsv"
    output:
        fasta="resources/primers.fas"
    log:
       "logs/prep-primer-fasta.log",
    run:
        import pandas as pd
        oligos = pd.read_table(input.tsv, usecols=['Name', 'Sequence'])
        with open(output.fasta, "w") as f:
            for index, row in oligos.iterrows():
                f.write(">" + row['Name'] + "\n" + row['Sequence'] + "\n")


rule create_dict:
    input:
        "resources/primers.fas",
    output:
        "resources/primers.dict",
    log:
        "logs/picard/create_dict.log",
    params:
        extra="",  # optional: extra arguments for picard.
    # optional specification of memory usage of the JVM that snakemake will respect with global
    # resource restrictions (https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#resources)
    # and which can be used to request RAM during cluster job submission as `{resources.mem_mb}`:
    # https://snakemake.readthedocs.io/en/latest/executing/cluster.html#job-properties
    resources:
        mem_mb=1024,
    wrapper:
        "v7.6.0/bio/picard/createsequencedictionary"


rule get_genome:
    """
    Download data from NCBI and place it to correct location
    """
    output:
        fasta="resources/genomes/{id}.fas",
        zip=temp("resources/datasets/{id}.zip"),
        dir=temp(directory("resources/datasets/{id}"))
    shell:
        """
        datasets download genome accession {wildcards.id} --include genome --filename {output.zip}
        unzip {output.dir}.zip -d {output.dir}
        mv {output.dir}/ncbi_dataset/data/{wildcards.id}/{wildcards.id}*_genomic.fna {output.fasta}
        """

rule lastdb_transcript:
    input:
        "resources/primers.fas"
    output:
        #"resources/primers.fas.prj"
        "resources/lastaldb.prj"
    params:
        protein_input=False,
        extra="resources/lastaldb"
    log:
        "logs/last/db.log"
    wrapper:
        "v8.0.3/bio/last/lastdb"


rule lastal_nucl_x_nucl:
    input:
        data="resources/genomes/{sample}.fas", # "input/{sample}.fas",
        lastdb="resources/lastaldb.prj"
    output:
        # only one of these outputs is allowed
        maf="results/{sample}/lastal.maf",
        #tab="test-transcript.tab",
        #blasttab="test-transcript.blasttab",
        #blasttabplus="test-transcript.blasttabplus",
    params:
        #Report alignments that are expected by chance at most once per LENGTH query letters. By default, LAST reports alignments that are expected by chance at most once per million query letters (for a given database). http://last.cbrc.jp/doc/last-evalues.html
        D_length=1000000,
        extra=""
    log:
        "logs/last/al-{sample}.log"
    threads: 8
    wrapper:
        "v8.0.3/bio/last/lastal"


rule maf_to_sam:
    input:
        maf="results/{sample}/lastal.maf",
        dict="resources/primers.dict",
    output:
        sam="results/{sample}/lastal.sam"
    conda:
        "envs/primers.yml"
    log:
        "logs/last/maf-to-sam-{sample}.log"
    shell:
        """
        maf-convert sam -f {input.dict} -r 'ID:{wildcards.sample} SM:{wildcards.sample}' {input.maf} > {output.sam} 2> {log}
        """


rule iupacsam:
    input:
        sam="results/{sample}/lastal.sam",
        primers="resources/primers.fas"
    output:
        iupac_sam="results/{sample}/iupac.sam"
    conda:
        "envs/primers.yml"
    log:
        "logs/sam-harmonization/iupac-sam-{sample}.log"
    shell:
        """
        sam-update-iupac.pl {input.sam} {input.primers} > {output.iupac_sam} 2> {log}
        """


rule parse_primers:
    input:
        sam="results/{sample}/iupac.sam",
        yaml="config/primers.yaml" # "resources/primers.yaml" Could be used instead
    output:
        parsed="results/{sample}/result.tsv"
    conda:
        "envs/primers.yml"
    log:
        "logs/primer-parsing/parse-primers-{sample}.log"
    shell:
        """
        perl workflow/scripts/sam-primers-and-probes.pl {input.sam} {input.yaml} > {output.parsed} 2> {log}
        """


rule extract_amplicon_seqs:
    input:
        tsv="results/{sample}/result.tsv",
        fas="resources/genomes/{sample}.fas", # "input/{sample}.fas"
    output:
        regions="results/{sample}/regions",
        amplicons="results/{sample}/amplicons.fas"
    conda:
        "envs/primers.yml"
    log:
        "logs/extract-amplicons/extract-amplicons-{sample}.log"
    shell:
        """
        cat {input.tsv} | awk -F'\\t' '{{print $2 "\\t" $1}}' | tail -n +2 >{output.regions}
        perl workflow/scripts/fasta_get_regions {input.fas} -tab={output.regions} > {output.amplicons} 2> {log}
        """
