include: "rules/common.smk"


# load rules
# -----------------------------------------------------
include: "rules/oligo-screening.smk"


rule all:
    input:
        expand("results/{sample}/result.tsv", sample=samples),
        expand("results/{sample}/amplicons.fas", sample=samples),
    default_target: True


